language:
- java
script:
- "./gradlew clean build test uploadArchives"
jdk:
- oraclejdk8
env:
  global:
  - secure: clcPRFwNTKcv6Vi2eJPwBdlJjgNYMjUJlWmN1n7DbBKuJfWT58KFhgS1Rm9KeUIBCqxXnm85K139oUgD4gZ/bPtjoNoLpfFYFhvsNbEgw/xov6CdUiKaf8C69rFoSgLT9tUL1wA7v+Hg0VkNg2rTHravoB5CRdUO0Z8oBKLY3Aw=
  - secure: nnNR7a1iWMMHoe4lCStAqajwInV859wvCqKX0BTS0dokHcpEdUFa6MYtU6lMGWM7EhdQrkok7XlLcNEg6I14jn3NqmF7qPvo+4EmWeA29bsvCXIZOmTHzXTYwlQ0DI/qJyMlnqPwvFjFxV7TupjBQTPVaJ/1YUKToB0KuOC9pUs=
